---
- name: Create EC2
  hosts: localhost
  gather_facts: False
  vars:
    keypair: キーペアを入力
    instance_type: t2.micro
    security_group: セキュリティーグループ名を入力
    image: AMIのイメージIDを入力
    region: ap-northeast-1（東京リージョン）
  tasks:
  - ec2:
      key_name: "{{ keypair }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: yes
      group: "{{ security_group }}"
      count: 1
      vpc_subnet_id: サブネットIDを入力
      assign_public_ip: yes
      region: "{{ region }}"
...
